### PR TITLE
add introduction links

### PR DESCRIPTION
**Pull request by afknapping**
cc @HerrBertling

### CODE REVIEW

**Review by HerrBertling — CHANGES_REQUESTED** [review]
The last link says "Check this the introduction", so I'd either skip the `this` or the `the` 😆

**Comment by HerrBertling** [comment]
Rest looks good and 🚀  for adding that link, of course 😍  Also: Add yourself to the credits at the bottom! 💸

**Comment by afknapping** [comment]
done

**Review by HerrBertling — APPROVED** [review]

**Comment by HerrBertling** [comment]
Tada 🎉

**Comment by robertkowalski** [comment]
deployed 3 hrs ago, should be online soon

**Pull request merged**
